version: '3.3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql-database/:/var/lib/mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: odmin
      MYSQL_USER: odmin
      MYSQL_PASSWORD: odmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    # volumes:
    #   - ./sessions
    depends_on:
      - db

# volumes:
#     db_data: {}