version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: prod_odmin_mysql
    volumes:
      - ./docker-data/mysql/:/var/lib/mysql
    ports:
      - 10001:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: odmin
      MYSQL_USER: odmin
      MYSQL_PASSWORD: odmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prod_odmin_phpmyadmin
    ports:
      - 10002:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker-data/phpmyadmin/:/sessions
    depends_on:
      - db

  odmin:
    build: ./
    image: odmin
    container_name: prod_odmin
    ports:
      - 10004:3030
    # volumes:
    #   - ./docker-data/:/odmin

# volumes:
#     db_data: {}